### ISSUE TITLE
Misleading exception message in corner cases

### ISSUE THREAD

**Issue by adamzovits** [awaitility/awaitility#109]
Consider a test case (" `await().atMost(5, SECONDS).untilCall(to(SUT).getSignals(), is(equalTo(expectedSignals)));` ") where the last check of the condition before the timeout fails and the next check is successful, but the overall await() call fails due to the timeout.
This results in an error message like this: "`org.awaitility.core.ConditionTimeoutException: our.company.and.packages.SUT.getSignals() expected <X> but was <X> within 5 seconds.`"
The error message could be updated to better reflect the fact that the check was not successful within the allocated time window and could contain the result of the last call to the condition evaluator that still happened within the time window of atMost.
See the discussion at: https://groups.google.com/forum/#!topic/awaitility/3TDz365y4pw

**Comment by johanhaleby** [comment]
Thanks for reporting!

**Comment by adamzovits** [comment]
This code reproduces the issue reliably (10/10) on my PC, but the exact values of the delays might depend on the performance of the system and so might need to be adjusted.
Results in `org.awaitility.core.ConditionTimeoutException: whatever.TestClass.getCounter() expected <44> but was <44> within 5 seconds.`

```
package whatever;

import static org.awaitility.Awaitility.await;
import static org.awaitility.proxy.AwaitilityClassProxy.to;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.is;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.awaitility.Duration;

public class TestClass {

    public static void main(final String[] args) throws java.lang.Exception {
        final Logger log = LogManager.getLogger();
        log.info("Starting awaitilityTest");
        final TestClass sut = new TestClass();
        try {
            await().atMost(Duration.FIVE_SECONDS).untilCall(to(sut).getCounter(), is(equalTo(44)));
            log.info("No exception was thrown");
        } catch (final Exception e) {
            log.catching(e);
        }
        log.info("Finished awaitilityTest");
    }

    public int getCounter() {
        try {
            if (counter > 42) { // the last call takes long enough to cause a timeout
                Thread.sleep(120);
            } else {
                Thread.sleep(12);
            }
        } catch (final InterruptedException e) {
            // should never happen
        }
        return ++counter;
    }

    private int counter = 0;
}
```

**Comment by jtnord** [comment]
Just hit this and spend a few hours trying to get to the bottom of my test failure :-0 

In doing so I have (I believe) made a more succinct test case:

```java

import org.junit.Test;
import java.util.concurrent.atomic.AtomicInteger;
import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.core.Is.is;

public class AwaitilityTest {

    @Test
    public void testIt() {
        AtomicInteger ai = new AtomicInteger();
        await("Hello").atMost(999, MILLISECONDS).pollInterval(100, MILLISECONDS).until(() -> {
            Thread.sleep(600L);
            if (ai.incrementAndGet() == 2) {
                return 100;
            }
            return -1;
        }, is(100));
    }

}

````
which fails with the following:

```
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Hello' didn't complete within 999 milliseconds because lambda expression in AwaitilityTest that uses java.util.concurrent.atomic.AtomicInteger: expected <100> but was <100>.

	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:89)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:856)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:631)
	at AwaitilityTest.testIt(AwaitilityTest.java:18)
```


Note the `expected <100> but was <100>`  rather than the expected `expected <100> but was <-1>`

**Comment by johanhaleby** [comment]
@jtnord Thanks a lot for investigating and for the test case. I'll have a look when I find time. 👍

**Comment by johanhaleby** [comment]
I think I've fixed this in master now. The condition evaluation should now be cancelled when the the wait time exceeds the max wait time.

**Comment by johanhaleby** [comment]
I've published the snapshot now. Please try version `3.1.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by johanhaleby** [comment]
I'm closing the issue for now, please tell me if it should be re-opened.

**Comment by calle2010** [comment]
I found this bug report because I keep getting test results like ": expected <4> but was <4> within 3 seconds." on our Jenkins build every now and then. Building upon the test case of @jtnord I tried this now with Awaitility 3.1.6:

    public class TestAwaitilty {
        final AtomicInteger ai = new AtomicInteger();
    
        @Test
        public void testIt() {
            with().conditionEvaluationListener(new ConditionEvaluationLogger())
                .await("Hello")
                .atMost(200, MILLISECONDS)
                .pollInterval(95, MILLISECONDS)
                .until(this::condition, is(100));
        }
    
        private Integer condition() {
            if (ai.incrementAndGet() == 2) {
                return 100;
            }
            return -1;
        }
}
`

What I see is one of three outcomes: 

a) Test is green with two lines from the Condition logger:

    Lambda expression in test1.TestAwaitilty: expected <100> but was <-1> (elapsed time 99 milliseconds, remaining time 101 milliseconds (last poll interval was 95 milliseconds))
    Lambda expression in test1.TestAwaitilty: reached its end value of <100> after 196 milliseconds (remaining time 4 milliseconds, last poll interval was 95 milliseconds)

b) Test is red with just one line from the Condition logger:

    Lambda expression in test1.TestAwaitilty: expected <100> but was <-1> (elapsed time 105 milliseconds, remaining time 95 milliseconds (last poll interval was 95 milliseconds))

c) (rare case, 1 out of 10) Test is red with two lines from the Condition logger:

    Lambda expression in test1.TestAwaitilty: expected <100> but was <-1> (elapsed time 99 milliseconds, remaining time 101 milliseconds (last poll interval was 95 milliseconds))
    Lambda expression in test1.TestAwaitilty: reached its end value of <100> after 198 milliseconds (remaining time 2 milliseconds, last poll interval was 95 milliseconds)

a) and b) are expected.
c) I don't understand since at least considering from the logger output the test should have succeeded.

I could imagine you may have to fine tune the poll interval depending on your machine to reprodue the results.

**Comment by Mitul-max** [comment]
Hi @johanhaleby , im still not clear on the solution provided by you for adding the snapshot, can you briefly explain here how do we use the fix for awaitility.
Thanks
